/**
 * Google OAuth Authentication Service for Expo / React Native
 * Hawem (حايم) Citizen-Science Platform
 *
 * Implements:
 * - Supabase OAuth 2.0 PKCE / token flow via Google
 * - Expo WebBrowser authentication session
 * - Deep link redirection (hawem:// and Expo Go)
 * - Automatic session setting in Supabase client
 */

import * as WebBrowser from 'expo-web-browser';
import { makeRedirectUri } from 'expo-auth-session';
import { supabase } from './supabase.ts';

// Complete any pending auth session if the browser redirected back
try {
  WebBrowser.maybeCompleteAuthSession();
} catch (e) {
  // Graceful no-op in non-browser environments
}

export interface GoogleAuthResult {
  success: boolean;
  user?: any;
  error?: string;
}

/**
 * Returns the exact OAuth redirect URI generated by Expo for this runtime
 */
export function getOAuthRedirectUri(): string {
  return makeRedirectUri({
    scheme: 'hawem',
    path: 'auth/callback',
    preferLocalhost: false,
  });
}

/**
 * Initiates the Google OAuth sign-in flow via Supabase
 */
export async function signInWithGoogle(): Promise<GoogleAuthResult> {
  try {
    const redirectUrl = getOAuthRedirectUri();
    console.log('[googleAuthService] OAuth Redirect URI:', redirectUrl);

    const { data, error } = await supabase.auth.signInWithOAuth({
      provider: 'google',
      options: {
        redirectTo: redirectUrl,
        skipBrowserRedirect: true,
      },
    });

    if (error || !data?.url) {
      console.warn('[googleAuthService] Supabase OAuth initiation error:', error);
      return {
        success: false,
        error: error?.message || 'Failed to initiate Google OAuth with Supabase',
      };
    }

    console.log('[googleAuthService] Opening WebBrowser with URL:', data.url);
    const authResult = await WebBrowser.openAuthSessionAsync(
      data.url,
      redirectUrl
    );

    console.log('[googleAuthService] Auth result type:', authResult.type);

    if (authResult.type === 'success' && authResult.url) {
      const url = authResult.url;
      console.log('[googleAuthService] Intercepted callback URL:', url);

      // Parse both query parameters (?code=...) and hash fragment (#access_token=...)
      const params: Record<string, string> = {};
      const queryPart = (url.split('#')[0] || '').split('?')[1] || '';
      const hashPart = url.split('#')[1] || '';
      const combined = [queryPart, hashPart].filter(Boolean).join('&');

      if (combined) {
        const pairs = combined.split('&');
        for (const pair of pairs) {
          const [k, v] = pair.split('=');
          if (k && v) {
            params[decodeURIComponent(k)] = decodeURIComponent(v);
          }
        }
      }

      if (params.error_description || params.error) {
        return {
          success: false,
          error: params.error_description || params.error,
        };
      }

      if (params.access_token && params.refresh_token) {
        const { data: sessionData, error: sessionErr } =
          await supabase.auth.setSession({
            access_token: params.access_token,
            refresh_token: params.refresh_token,
          });

        if (sessionErr) {
          return { success: false, error: sessionErr.message };
        }

        return { success: true, user: sessionData.user };
      } else if (params.code) {
        const { data: exchangeData, error: exchangeErr } =
          await supabase.auth.exchangeCodeForSession(params.code);

        if (exchangeErr) {
          return { success: false, error: exchangeErr.message };
        }

        return { success: true, user: exchangeData.user };
      }
    }

    if (authResult.type === 'cancel' || authResult.type === 'dismiss') {
      return {
        success: false,
        error:
          'Sign-in was closed or could not connect. If Google showed "Something went wrong", make sure your Gmail is added under Google Cloud Console > OAuth consent screen > Test users, and Supabase Redirect URLs includes exp://** and hawem://**. You can also register directly with your Gmail via "Create Account" above.',
      };
    }

    return { success: false, error: 'Authentication could not be completed' };
  } catch (err: any) {
    console.warn('[googleAuthService] Google OAuth error:', err);
    return { success: false, error: err?.message || 'Google sign-in failed' };
  }
}
